### ISSUE TITLE
Align column width in tabular output

### ISSUE THREAD

**Issue by jobrs** [sapcc/maia#26]
Currently tabular output is hard to read because the columns are not formatted to have equal width.

```
Col1 Column2 C3
longvalue sval avgval
sval longvalue avgval
```

Make sure that columns in tabular output format are aligned, so that a column has the same width across all rows.
```
Col1          Column2    C3
longvalue     sval       avgval
sval          longvalue  avgval
```
Make the maximum width configurable, so that single large columns do not break the entire layout.

**Comment by jobrs** [comment]
use e.g. https://golang.org/pkg/text/tabwriter/

**Comment by notque** [comment]
we're moving to the update ui, so this isn't relevant anymore
