### ISSUE TITLE
cannot select projects if project dropdown gets too full

### ISSUE THREAD

**Issue by majewsky** [sapcc/maia#32]
To reproduce:

1. Log on to Maia in a region and domain where you have access to a lot of projects (for me, in eu-de-1/monsoon3).
2. Open the project dropdown.

The list of projects is too big to fit on the screen, and I cannot select most of them because the dropdown list does not scroll or respond to arrow keys. (Or if it does, it's not discoverable for me.)

**Comment by majewsky** [comment]
1c4a556 goes most of the way, but `max-height: 800px` still fails e.g. on my Macbook screen because the viewport height is smaller than 800px. What about `max-height: 80vh`?

**Comment by jobrs** [comment]
good idea, was not aware of that possibility. The fix is deployed on eu-de-1.

Please close the ticket if it works for you, too!

**Comment by majewsky** [comment]
Yep, looks good. I can select all projects now.
