### ISSUE TITLE
MAIA client is not compatible with 1.12 (tested with go1.12.1 darwin/amd64)

### ISSUE THREAD

**Issue by dhalimi** [sapcc/maia#43]
**Step to reproduce:**
1. Use golang 1.12.1
2. Clone latest MAIA (f5fd9a4d5ddc955e5539eb1af77685e385262da5)
3. Use make to build MAIA client 
4. make sure the build completed by running the command maia, and make sure the output guidelines.
4. Source converged cloud openrc file to connect to your project
5. Run MAIA command to get all metrics - maia metric-names

**Expected**: list all metrics
**Actual**: getting an error: runtime error: slice bounds out of range

**Comment by jobrs** [comment]
updated to use golang 1.12.3
