### ISSUE TITLE
Support OpenStack application credentials

### ISSUE THREAD

**Issue by jobrs** [sapcc/maia#51]
Support OpenStack [application credentials](https://docs.openstack.org/keystone/queens/user/application_credentials.html), so that users can easily create restricted technical users to use for authentication of Grafana data sources or Prometheus federation.

Key Results
- [x] OS_APPLICATION_CREDENTIAL_ID, OS_APPLICATION_CREDENTIAL_NAME and OS_APPLICATION_CREDENTIAL_SECRET standard environment variables are supported
- [x] application credentials can be passed via basic authentication (or another mechanism supported both by Prometheus as client and Grafana)

Implementation

Gophercloud already support application credentials since https://github.com/gophercloud/gophercloud/pull/1224. Not tested yet!

**Comment by jobrs** [comment]
@kayrus fyi

**Comment by kayrus** [comment]
In order to handle auth types properly, I created an issue in gophercloud: https&#58;//github.com\/gophercloud&#47;<span>gophercloud&#47;issues/1566</span>

**Comment by jobrs** [comment]
implemented, tested and integrated successfully with PR #61, #65, #66
