### ISSUE TITLE
PR 52 reverted regarding move to gomod/build changes.

### ISSUE THREAD

**Issue by notque** [sapcc/maia#54]
https://github.com/sapcc/maia/pull/52

Breaking our concourse builds, which I think is due to the gopath changes which are breaking the temp build. Needs to be looked at further, reverted for now.

**Comment by kayrus** [comment]
Could you please share the logs? Regular Linux builds and builds inside the docker container worked fine in Linux env.

**Comment by notque** [comment]
Yes, concourse was blowing up with the PR merged, and it wouldn't deploy maia. I ended up backing it out at the time, and haven't addressed it yet. Do you want to look at this together on Monday morning your time?
